# docker-compose.yml

version: "3"

services:
  external:
    container_name: svelte-deploy
    # The name of the image that will be created when building this container
    image: node-svelte-deploy
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Europe/Brussels
    restart: unless-stopped
    ports:
      - '3000:5050'